# Keep the same markdown settings
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-redirect-from

# Pagination
paginate_path: "/blog/:num"
paginate: 5

# Sass location - theme ?
sass:
  sass_dir: assets/_scss
  style: compressed

# Exclude
exclude: ["Gemfile*", "vendor", ".github", ".vscode", "README*", "LICENSE"]
