title: "Erwan Martin"
description: "PhD in Neuroscience"
baseurl: "" # or your repo name if using project pages
url: ""

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
